services:
  - type: web
    name: advocacia-erp
    runtime: docker
    plan: free
    healthCheckPath: /index.php
    envVars:
      - key: DOLIBARR_DB_HOST
        fromDatabase:
          name: advocacia-db
          property: host
      - key: DOLIBARR_DB_PORT
        fromDatabase:
          name: advocacia-db
          property: port
      - key: DOLIBARR_DB_USER
        fromDatabase:
          name: advocacia-db
          property: user
      - key: DOLIBARR_DB_PASS
        fromDatabase:
          name: advocacia-db
          property: password
      - key: DOLIBARR_DB_NAME
        fromDatabase:
          name: advocacia-db
          property: database
      - key: DOLIBARR_URL_ROOT
        value: https://advocacia-erp.onrender.com
      - key: DOLIBARR_ADMIN_PASSWORD
        value: admin
      - key: PHP_MEMORY_LIMIT
        value: "256M"
      - key: PHP_MAX_EXECUTION_TIME
        value: "120"

databases:
  - name: advocacia-db
    databaseName: advocacia_db
    plan: free
    ipAllowList: []